version: "{build}"
skip_tags: true
skip_branch_with_pr: true
clone_folder: c:\gopath\src\github.com\vcabbage\dogstatsd
environment:
  GOPATH: c:\gopath
install:
- rmdir c:\go /s /q
- appveyor DownloadFile https://storage.googleapis.com/golang/go1.11.windows-amd64.zip
- 7z x go1.11.windows-amd64.zip -y -oC:\ > NUL
- set PATH=%GOPATH%\bin;%PATH%
- go version
- go env
- go get -v -d -t ./...
build: off
test_script:
- go test -v -race ./...
